# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js Backend ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: backend/package-lock.json
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      working-directory: ./backend
    - run: npm run build --if-present
      working-directory: ./backend
    - run: npm test
      working-directory: ./backend
    - run: npm run lint
      working-directory: ./backend

    - name: Use Node.js Frontend ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: frontend/package-lock.json
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      working-directory: ./frontend
    - run: npm run build --if-present
      working-directory: ./frontend
    - run: npm test
      working-directory: ./frontend
    # Active bug with eslint https://github.com/eslint/eslint/issues/19322 - we will have to accept no linting for now
    # - run: npm run lint
    #   working-directory: ./frontend
